### ISSUE TITLE
Create Worlds view

### ISSUE THREAD

**Issue by vreynolds** [FarseerTeam/Farseer#15]
The default view for the app should be a Worlds view (e.g. Pillar, Hogwarts, Fight Club) where the user may select from a list of available worlds which one s/he wants to interact with.

For now, the links may be inactive. No need to change other views.

**Comment by jgartee** [comment]
We've (@dimpar and I) are changing the default landing page to go to a worlds selection/creation page.  The existing worlds will be hyperlinks, pointing to the base route for the selected world.

**Comment by robertfmurdock** [comment]
Sounds good!
