### ISSUE TITLE
History View

### ISSUE THREAD

**Issue by robertfmurdock** [FarseerTeam/Farseer#20]
Show a history page that uses the history endpoint. This should display all the changes made, along with the date of the change and the identity (with avatar) of the person who made the change.

**Comment by vreynolds** [comment]
Hey @robertfmurdock, can you checkout branch auth-action-history? I could use some direction discussion.

What that branch currently does: when you're logged in and you create a player, it will insert an entry into the _activity_ table with the logged in email and an action description.

I'm wondering about compounding most of the info into a description vs having a more discreet format for history chunks (like action: create | delete | etc, entity: player | world | etc). In former case, you have a well formatted history blurb, but it's fairly inflexible. In the latter case, you have more flexibility to change how this info is presented to the user, but you have to build the actual blurbs for every row.

Thoughts?

**Comment by robertfmurdock** [comment]
Are you talking about one action table vs multiple action tables? Here are some thoughts:

- The parameters of the action are pretty interesting, aka "which player was created", or "where was this player moved from & to"
- It'll probably be most useful to have some kind of enum-like value to indicate the action taken. That way if we want to change the word presented to the user for a particular action we can change the UI without having to update the database in any way
- I'm usually inclined to keeping information in the database highly specified and flexible, and leave all formatting and making pretty to the UI application

Does this help answer the questions? Or am I missing something. Its Friday morning, I'm a little spacey. :-)
