### ISSUE TITLE
Player's team path '/' hides all other team members

### ISSUE THREAD

**Issue by dimpar** [FarseerTeam/Farseer#33]
We need to fix a bug when we add/modify a player's team path to only '/', the other team players won't show up on the player's map screen.

**Comment by crazyDiamond** [comment]
@robertfmurdock @vreynolds,
How about the save button is enabled when the user types in something after the forward slash?
Also, disable the save button when the text is only a forward slash?

**Comment by robertfmurdock** [comment]
Worth a shot

**Comment by crazyDiamond** [comment]
@vreynolds @robertfmurdock,
PR #49 should address this issue.
