### ISSUE TITLE
Clicking on a team's name should display just that team

### ISSUE THREAD

**Issue by crazyDiamond** [FarseerTeam/Farseer#40]
Also this should update the URL so that a bookmark can be made directly to that team.

**Comment by crazyDiamond** [comment]
Have submitted a PR for this.
https://github.com/FarseerTeam/Farseer/pull/41

**Comment by vreynolds** [comment]
@robertfmurdock this is now deployed to heroku

**Comment by robertfmurdock** [comment]
Woo! Thanks all.

**Comment by crazyDiamond** [comment]
Great! Can we close this issue now?

**Comment by robertfmurdock** [comment]
Da.
