### ISSUE TITLE
New player input fields do not clear out after adding a player

### ISSUE THREAD

**Issue by vreynolds** [FarseerTeam/Farseer#44]
<img width="629" alt="screen shot 2016-06-30 at 1 11 24 pm" src="https://cloud.githubusercontent.com/assets/6738917/16500951/3dd10286-3ec4-11e6-9e75-7fab9d2b09cc.png">

Name/email/team fields should be cleared after adding a player.

**Comment by crazyDiamond** [comment]
@vreynolds, I've started work on this. FYI.

**Comment by crazyDiamond** [comment]
Have submitted [PR](https://github.com/FarseerTeam/Farseer/pull/51) for this.
