### ISSUE TITLE
Re-enable protractor spec with alert

### ISSUE THREAD

**Issue by vreynolds** [FarseerTeam/Farseer#46]
Protractor worlds.spec.js test that involves dismissing an alert has been disabled, since latest Chrome release (52) broke webdriver functionality around alerts (https://github.com/angular/protractor/issues/1486). Upgrading to protractor 4 and latest Chrome webdriver didn't fix the problem.

Re-enable the test when there is a working Chrome webdriver version, or another solution.

**Comment by crazyDiamond** [comment]
I spent a bunch of time trying to figure out the issue without actually pulling from upstream/master + reading your comments! Thanks for the update @vreynolds .

**Comment by crazyDiamond** [comment]
@vreynolds, after I pulled from upstream, I am seeing the following error when running all tests.

 " E/launcher - Process exited with error code 1
/Users/jeevanadarajah/Projects/forks/Farseer/node_modules/q/q.js:155
                throw e;
No selenium server jar found at the specified location (/Users/jeevanadarajah/Projects/forks/Farseer/node_modules/grunt-protractor-runner/node_modules/protractor/selenium/selenium-server-standalone-2.52.0.jar). Check that the version number is up to date."

I have tried removing my node_modules folder and reinstalling/updating npm.
What am I missing?

**Comment by vreynolds** [comment]
I'm pretty sure I came across this before. Have you tried:
`./node_modules/grunt-protractor-runner/scripts/webdriver-manager-update`

**Comment by crazyDiamond** [comment]
That worked wonderfully!
